version: "2"
linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF1003"
      - linters:
          - errcheck
        text: "resp.Body.Close"
      - linters:
          - errcheck
        text: "file.Close"
